=== TheSecretSquad/Game-Players-Hub/schemas/gameCatalog.xsd
<?xml version="1.0"?>
<!--
  ______                   ______  _                             _     _       _                         
 / _____)                 (_____ \| |                           | |   | |     | |                        
| /  ___  ____ ____   ____ _____) ) | ____ _   _  ____  ____ ___| |__ | |_   _| | _     ____  ___  ____  
| | (___)/ _  |    \ / _  )  ____/| |/ _  | | | |/ _  )/ ___)___)  __)| | | | | || \   / ___)/ _ \|    \ 
| \____/( ( | | | | ( (/ /| |     | ( ( | | |_| ( (/ /| |  |___ | |   | | |_| | |_) )_( (___| |_| | | | |
 \_____/ \_||_|_|_|_|\____)_|     |_|\_||_|\__  |\____)_|  (___/|_|   |_|\____|____/(_)\____)\___/|_|_|_|
                                          (____/                                                         

File:   GPHCatalog.xml
Author: Peter DiSalvo
Date:   April 2012

Purpose:	Schema for a game catalog, which is essentially an inventory.
			The catalog has catalogs within it, namely a separate catalog for
			storing data on game publishing companies, game developing companies
			and gaming platforms. They are all interrelated using ID and IDREF types.

-->

<xs:schema targetNamespace="http://www.gameplayershub.com/gameCatalog"
           elementFormDefault="qualified"
           xmlns="http://www.gameplayershub.com/gameCatalog"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:sha="http://www.gameplayershub.com/sharedTypes"
           xmlns:sal="http://www.gameplayershub.com/sale">

  <xs:import namespace="http://www.gameplayershub.com/sharedTypes" schemaLocation="sharedTypes.xsd" />
  <xs:import namespace="http://www.gameplayershub.com/sale" schemaLocation="sale.xsd" />

  <!--__TYPE DECLARATIONS FOR: gameCatalog-->

  <!--  A game catalog has a list of game releases
        that references a list of game titles, platforms,
        and publishers.
  -->
  <xs:element name="gameCatalog" type="gameCatalog" />

  <xs:complexType name="gameCatalog">
    <xs:sequence>
      <xs:element name="game" type="game" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="platformsCatalog">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="platform" type="platform" minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="publishersCatalog">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="publisher" type="studio" minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="developersCatalog">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="developer" type="studio" minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element ref="sal:salesCatalog" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>


  <!--__TYPE DECLARATIONS FOR: game-->

  <!--  A game title is produced by a set of publishers
        and developers.
        Each game release is released under a title.
        Each title is unique, and specifying it once
        prevents duplication and errors in spelling.
        Game titles can be released by publishers on different
        platforms at different times.
  -->
  <xs:complexType name="game">
    <xs:sequence>
      <xs:element name="title" type="xs:string" />
      <xs:element name="release" type="gameRelease" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="publishers" type="xs:IDREFS" use="optional" />
    <xs:attribute name="developers" type="xs:IDREFS" use="optional" />
    <xs:attribute name="genres" use="required">
      <xs:simpleType>
        <xs:list itemType="genre" />
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="homepage" type="sha:webLink" use ="optional" />
  </xs:complexType>

  <!--  A game title has many game is released on various
        platforms, at various times and sold at different prices
   -->
  <xs:complexType name="gameRelease">
    <xs:sequence>
      <xs:element name="msrp" type="sha:price" minOccurs="0" maxOccurs="1" />
      <xs:element name="releaseDate" type="xs:date" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="id" type="gameReleaseID" use="required" />
    <xs:attribute name="platform" type="gameReleaseIDREF" use ="required" />
    <xs:attribute name="image" type="xs:anyURI" use="required" />
  </xs:complexType>

  <!-- Game release ID format -->
  <xs:simpleType name="gameReleaseID">
    <xs:restriction base="xs:ID">
      <xs:pattern value="\w*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Game release IDREF format should contain only word characters-->
  <xs:simpleType name="gameReleaseIDREF">
    <xs:restriction base="xs:IDREF">
      <xs:pattern value="\w*" />
    </xs:restriction>
  </xs:simpleType>

  <!-- List of game release IDREF -->
  <xs:simpleType name="gameReleaseIDREFS">
    <xs:list itemType="gameReleaseIDREF" />
  </xs:simpleType>

  <xs:simpleType name="genre">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Action" />
      <xs:enumeration value="Adventure" />
      <xs:enumeration value="Educational" />
      <xs:enumeration value="Fighting" />
      <xs:enumeration value="Hack-and-Slash" />
      <xs:enumeration value="Horror" />
      <xs:enumeration value="Interactive-Drama" />
      <xs:enumeration value="MMO" />
      <xs:enumeration value="Open-World" />
      <xs:enumeration value="Puzzle" />
      <xs:enumeration value="Psychological-Thriller" />
      <xs:enumeration value="Racing" />
      <xs:enumeration value="RPG" />
      <xs:enumeration value="Shooter" />
      <xs:enumeration value="Science-Fiction" />
      <xs:enumeration value="Simulation-Construction" />
      <xs:enumeration value="Simulation-Life" />
      <xs:enumeration value="Simulation-Vehicle" />
      <xs:enumeration value="Sports" />
      <xs:enumeration value="Strategy" />
      <xs:enumeration value="Survival" />
    </xs:restriction>
  </xs:simpleType>


  <!--__TYPE DECLARATIONS FOR: platform__-->

  <!--  A gaming platform is made by a manufacturer, has a model,
        and is of a certain class of devices. If the class is a
        PC, the manufacturer and model elements can be replaced
        with an operating system declaration.
  -->
  <xs:complexType name="platform">
    <xs:sequence>
      <xs:element name="manufacturer" type="xs:string" />
      <xs:element name="system" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required" />
    <xs:attribute name="class" type="platformClass" use="required" />
  </xs:complexType>

  <xs:simpleType name="platformClass">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Console" />
      <xs:enumeration value="Handheld" />
      <xs:enumeration value="Mobile" />
      <xs:enumeration value="PC" />
    </xs:restriction>
  </xs:simpleType>

  <!--__TYPE DECLARATIONS FOR: studio__-->

  <!--  Studio type is used for publishing
        and developer studios.
  -->

  <xs:complexType name="studio">
    <xs:simpleContent>
      <xs:extension base="sha:requiredString">
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="homepage" type="sha:webLink" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!--__TYPE DECLARATIONS FOR: scores-->

  <!--  Score consists of a criteria and a score value
        for that criteria
  -->

  <!--Subscore value is between 0 and 10-->
  <xs:simpleType name="scoreValue">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="10" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="criteria">
    <xs:restriction base ="xs:string">
      <xs:enumeration value="Controls" />
      <xs:enumeration value="Gameplay" />
      <xs:enumeration value="Graphics" />
      <xs:enumeration value="Innovation" />
      <xs:enumeration value="Multiplayer" />
      <xs:enumeration value="Presentation" />
      <xs:enumeration value="SinglePlayer" />
      <xs:enumeration value="Sound" />
      <xs:enumeration value="Story" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== TheSecretSquad/Game-Players-Hub/games.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  ______                   ______  _                             _     _       _                         
 / _____)                 (_____ \| |                           | |   | |     | |                        
| /  ___  ____ ____   ____ _____) ) | ____ _   _  ____  ____ ___| |__ | |_   _| | _     ____  ___  ____  
| | (___)/ _  |    \ / _  )  ____/| |/ _  | | | |/ _  )/ ___)___)  __)| | | | | || \   / ___)/ _ \|    \ 
| \____/( ( | | | | ( (/ /| |     | ( ( | | |_| ( (/ /| |  |___ | |   | | |_| | |_) )_( (___| |_| | | | |
 \_____/ \_||_|_|_|_|\____)_|     |_|\_||_|\__  |\____)_|  (___/|_|   |_|\____|____/(_)\____)\___/|_|_|_|
                                          (____/                                                         

File:    games.xml
Author:  Peter DiSalvo
Date:    April 2012

Purpose:  Game catalog file.
-->

<?xml-stylesheet type="text/xsl" href="games.xslt"?>
<gameCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.gameplayershub.com/gameCatalog schemas\gameCatalog.xsd"
             xmlns:sal="http://www.gameplayershub.com/sale"
             xmlns="http://www.gameplayershub.com/gameCatalog">

  <game genres="Fighting" publishers="pu1" homepage="http://www.capcom.co.jp/iphone/sf4_en">
    <title>Street Fighter IV</title>
    <release id="rl1" platform="pl3" image="images/games/streetFighter4Cover_iOS.jpg">
      <msrp currency="USD">9.99</msrp>
      <releaseDate>2010-03-09</releaseDate>
    </release>
    <release id="rl7" platform="pl1" image="images/games/streetFighter4Cover_PS3.jpg">
      <msrp currency="USD">29.99</msrp>
      <releaseDate>2010-03-09</releaseDate>
    </release>
    <release id="rl8" platform="pl2" image="images/games/streetFighter4Cover_XBox360.jpg">
      <msrp currency="USD">29.99</msrp>
      <releaseDate>2010-03-09</releaseDate>
    </release>
  </game>

  <game genres="Action Adventure Hack-and-Slash" publishers="pu2" developers="dv1" homepage="http://www.godofwar.com">
    <title>God of War III</title>
    <release id="rl2" platform="pl1" image="images/games/godOfWar3Cover_PS3.jpg">
      <msrp currency="USD">29.99</msrp>
      <releaseDate>2010-03-16</releaseDate>
    </release>
  </game>

  <game genres="Interactive-Drama Psychological-Thriller" publishers="pu2" developers="dv2">
    <title>Heavy Rain</title>
    <release id="rl3" platform="pl1" image="images/games/heavyRainCover_PS3.jpg">
      <msrp currency="USD">79.99</msrp>
      <releaseDate>2010-02-23</releaseDate>
    </release>
  </game>

  <game genres="Shooter" publishers="pu5" developers="dv5" homepage="http://www.battlefield.com">
    <title>Battlefield 3</title>
    <release id="rl4" platform="pl7" image="images/games/battlefield3Cover_PC.jpg">
      <msrp currency="USD">59.99</msrp>
      <releaseDate>2011-10-25</releaseDate>
    </release>
    <release id="rl5" platform="pl1" image="images/games/battlefield3Cover_PS3.jpg">
      <msrp currency="USD">59.99</msrp>
      <releaseDate>2011-10-25</releaseDate>
    </release>
    <release id="rl6" platform="pl2" image="images/games/battlefield3Cover_XBox360.jpg">
      <msrp currency="USD">59.99</msrp>
      <releaseDate>2011-10-25</releaseDate>
    </release>
  </game>

  <game genres="Action RPG" publishers="pu6 pu7" developers="dv6">
    <title>Call for Heroes: Pompolic Wars</title>
    <release id="rl9" platform="pl7" image="images/games/callForHeroesCover_PC.jpg">
      <msrp currency="USD">19.99</msrp>
      <releaseDate>2007-06-26</releaseDate>
    </release>
    <release id="rl10" platform="pl9" image="images/games/callForHeroesCover_Wii.jpg">
      <msrp currency="USD">19.99</msrp>
      <releaseDate>2007-06-26</releaseDate>
    </release>
  </game>

  <game genres="Action Adventure Open-World" publishers="pu8" developers="dv7" homepage="http://www.prototypegame.com">
    <title>Prototype 2</title>
    <release id="rl11" platform="pl7" image="images/games/prototype2Cover_PC.jpg">
      <msrp currency="USD">49.99</msrp>
      <releaseDate>2012-07-24</releaseDate>
    </release>
    <release id="rl12" platform="pl1" image="images/games/prototype2Cover_PS3.jpg">
      <msrp currency="USD">59.99</msrp>
      <releaseDate>2012-04-24</releaseDate>
    </release>
    <release id="rl13" platform="pl2" image="images/games/prototype2Cover_XBox360.jpg">
      <msrp currency="USD">59.99</msrp>
      <releaseDate>2012-04-24</releaseDate>
    </release>
  </game>

  <game genres="Survival Horror" publishers="pu9" developers="dv8" homepage="http://spiritcamera.nintendo.com">
    <title>Spirit Camera: The Cursed Memoir</title>
    <release id="rl14" platform="pl11" image="images/games/spiritCameraTCMCover_3DS.jpg">
      <msrp currency="USD">39.99</msrp>
      <releaseDate>2012-04-13</releaseDate>
    </release>
  </game>
  
  <platformsCatalog>
    <platform id="pl1" class="Console">
      <manufacturer>Sony</manufacturer>
      <system>Playstation 3</system>
    </platform>
    <platform id="pl2" class="Console">
      <manufacturer>Microsoft</manufacturer>
      <system>XBox 360</system>
    </platform>
    <platform id="pl3" class="Mobile">
      <manufacturer>Apple</manufacturer>
      <system>iOS</system>
    </platform>
    <platform id="pl4" class="Mobile">
      <manufacturer>Google</manufacturer>
      <system>Android</system>
    </platform>
    <platform id="pl5" class="Handheld">
      <manufacturer>Sony</manufacturer>
      <system>Playstation Vita</system>
    </platform>
    <platform id="pl6" class="Handheld">
      <manufacturer>Sony</manufacturer>
      <system>Playstation Portable (PSP)</system>
    </platform>
    <platform id="pl7" class="PC">
      <manufacturer>Microsoft</manufacturer>
      <system>Windows</system>
    </platform>
    <platform id="pl8" class="PC">
      <manufacturer>Apple</manufacturer>
      <system>Mac OS</system>
    </platform>
    <platform id="pl9" class="Console">
      <manufacturer>Nintendo</manufacturer>
      <system>Wii</system>
    </platform>
    <platform id="pl10" class="Handheld">
      <manufacturer>Nintendo</manufacturer>
      <system>DS</system>
    </platform>
    <platform id="pl11" class="Handheld">
      <manufacturer>Nintendo</manufacturer>
      <system>3DS</system>
    </platform>
  </platformsCatalog>

  <publishersCatalog>
    <publisher id="pu1" homepage="http://www.capcom.com">Capcom</publisher>
    <publisher id="pu2" homepage="http://us.playstation.com">Sony Computer Entertainment</publisher>
    <publisher id="pu3" homepage="http://www.microsoft.com/games">Microsoft Studios</publisher>
    <publisher id="pu5" homepage="http://www.ea.com">Electronic Arts (EA)</publisher>
    <publisher id="pu6" homepage="http://www.strategyfirst.com">Strategy First</publisher>
    <publisher id="pu7" homepage="http://datadesign.uk.com">Data Design Interactive</publisher>
    <publisher id="pu8" homepage="http://www.activision.com/atvihub/home.do">Activision</publisher>
    <publisher id="pu9" homepage="http://www.nintendo.com/?country=US&amp;lang=en">Nintendo</publisher>
  </publishersCatalog>

  <developersCatalog>
    <developer id="dv1" homepage="http://www.worldwidestudios.net/santamonica">Santa Monica Studios</developer>
    <developer id="dv2" homepage="http://www.quanticdream.com">Quantic Dream</developer>
    <developer id="dv3" homepage="http://www.remedygames.com">Remedy Entertainment</developer>
    <developer id="dv5" homepage="http://www.dice.se">EA Digital Illusions CE (DICE)</developer>
    <developer id="dv6" homepage="http://www.quotixsoftware.com">Quotix Software</developer>
    <developer id="dv7" homepage="http://www.radical.ca">Radical Entertainment</developer>
    <developer id="dv8" homepage="http://www.koeitecmo.co.jp/e/index.html">Tecmo Koei</developer>
  </developersCatalog>

  <sal:salesCatalog>
    <sal:sale saleID="sl1" forItem="rl1" link="http://itunes.apple.com/us/app/street-fighter-iv/id354655665?mt=8">
      <sal:vendorName>iTunes</sal:vendorName>
      <sal:price currency="USD">4.99</sal:price>
      <sal:startDate>2012-03-12</sal:startDate>
      <sal:endDate>2012-04-12</sal:endDate>
    </sal:sale>
    <sal:sale saleID="sl2" forItem="rl7" link="http://www.amazon.com/Street-Fighter-IV-GH-Playstation-3/dp/B0012N5MIO">
      <sal:vendorName>Amazon</sal:vendorName>
      <sal:price currency="USD">10.99</sal:price>
    </sal:sale>
    <sal:sale saleID="sl3" forItem="rl8" link="http://www.amazon.com/Street-Fighter-IV-PH-Xbox-360/dp/B0012N3ZXS/ref=sr_1_1_title_0?s=videogames&amp;ie=UTF8&amp;qid=1335148590&amp;sr=1-1">
      <sal:vendorName>Amazon</sal:vendorName>
      <sal:price currency="USD">15.56</sal:price>
    </sal:sale>
    <sal:sale saleID="sl4" forItem="rl9" link="http://www.amazon.com/Call-For-Heroes-Pompollic-Wars-Pc/dp/B000P18Y8O/ref=sr_1_2?ie=UTF8&amp;qid=1335208116&amp;sr=8-2">
      <sal:vendorName>Amazon</sal:vendorName>
      <sal:price currency="USD">5.43</sal:price>
    </sal:sale>
    <sal:sale saleID="sl5" forItem="rl11" link="http://www.amazon.com/Prototype-2-Pc/dp/B004FUGKSW/ref=sr_1_1?s=videogames&amp;ie=UTF8&amp;qid=1335761335&amp;sr=1-1">
      <sal:vendorName>Amazon</sal:vendorName>
      <sal:price currency="USD">49.96</sal:price>
    </sal:sale>
    <sal:sale saleID="sl6" forItem="rl13" link="http://www.amazon.com/Prototype-2-Xbox-360/dp/B004FUL9YW/ref=sr_1_1?s=videogames&amp;ie=UTF8&amp;qid=1335761396&amp;sr=1-1">
      <sal:vendorName>Amazon</sal:vendorName>
      <sal:price currency="USD">52.75</sal:price>
    </sal:sale>
    <sal:sale saleID="sl7" forItem="rl12" link="http://www.amazon.com/Prototype-2-Playstation-3/dp/B004FUI84G/ref=sr_1_1?s=videogames&amp;ie=UTF8&amp;qid=1335761455&amp;sr=1-1">
      <sal:vendorName>Amazon</sal:vendorName>
      <sal:price currency="USD">55.30</sal:price>
    </sal:sale>
